// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartNarrator.Infrastructure.Persistence;

#nullable disable

namespace SmartNarrator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartNarratorDbContext))]
    [Migration("20260520150729_AddBackgroundJobProgressPhase")]
    partial class AddBackgroundJobProgressPhase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartNarrator.Domain.Entities.AudioArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("EndOffset")
                        .HasColumnType("integer");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("StartOffset")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UtteranceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.ToTable("audio_artifacts", (string)null);
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.BackgroundJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("ProgressPhase")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.HasIndex("Status", "CreatedUtc");

                    b.ToTable("background_jobs", (string)null);
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.CharacterProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AiExternalKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("AliasesJson")
                        .HasColumnType("text");

                    b.Property<string>("Breathiness")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GenderPresentation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAiSuggested")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SpeakingPace")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("UserApproved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkId", "AiExternalKey")
                        .IsUnique();

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.NarrativePassageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Breathiness")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("EndOffset")
                        .HasColumnType("integer");

                    b.Property<string>("GenderPresentation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAiSuggested")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("NarratorCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("PerspectiveNotes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SpeakingPace")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("StartOffset")
                        .HasColumnType("integer");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NarratorCharacterId");

                    b.HasIndex("WorkId", "StartOffset");

                    b.ToTable("narrative_passages", (string)null);
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.SourceDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("StoredRelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.ToTable("source_documents", (string)null);
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.TextSegmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EndOffset")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StartOffset")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("text_segments", (string)null);
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.UtteranceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<int>("EndOffset")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAiSuggested")
                        .HasColumnType("boolean");

                    b.Property<string>("SpeakerKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("StartOffset")
                        .HasColumnType("integer");

                    b.Property<bool>("UserApproved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("WorkId", "StartOffset");

                    b.ToTable("utterances", (string)null);
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.WorkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("works", (string)null);
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.AudioArtifactEntity", b =>
                {
                    b.HasOne("SmartNarrator.Domain.Entities.WorkEntity", "Work")
                        .WithMany("AudioArtifacts")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.BackgroundJobEntity", b =>
                {
                    b.HasOne("SmartNarrator.Domain.Entities.WorkEntity", "Work")
                        .WithMany("BackgroundJobs")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Work");
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.CharacterProfileEntity", b =>
                {
                    b.HasOne("SmartNarrator.Domain.Entities.WorkEntity", "Work")
                        .WithMany("Characters")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.NarrativePassageEntity", b =>
                {
                    b.HasOne("SmartNarrator.Domain.Entities.CharacterProfileEntity", "NarratorCharacter")
                        .WithMany()
                        .HasForeignKey("NarratorCharacterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartNarrator.Domain.Entities.WorkEntity", "Work")
                        .WithMany("NarrativePassages")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NarratorCharacter");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.SourceDocumentEntity", b =>
                {
                    b.HasOne("SmartNarrator.Domain.Entities.WorkEntity", "Work")
                        .WithMany("SourceDocuments")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.TextSegmentEntity", b =>
                {
                    b.HasOne("SmartNarrator.Domain.Entities.WorkEntity", "Work")
                        .WithMany("Segments")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.UtteranceEntity", b =>
                {
                    b.HasOne("SmartNarrator.Domain.Entities.CharacterProfileEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartNarrator.Domain.Entities.WorkEntity", "Work")
                        .WithMany("Utterances")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("SmartNarrator.Domain.Entities.WorkEntity", b =>
                {
                    b.Navigation("AudioArtifacts");

                    b.Navigation("BackgroundJobs");

                    b.Navigation("Characters");

                    b.Navigation("NarrativePassages");

                    b.Navigation("Segments");

                    b.Navigation("SourceDocuments");

                    b.Navigation("Utterances");
                });
#pragma warning restore 612, 618
        }
    }
}
